### ISSUE TITLE
Structure page converted to use blocks

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/website#705]
## Description

As a contributor I want that the website is setup cleanly

## Acceptance criteria

- [ ] Structure page converted to use blocks

**Comment by keyboardguy25** [comment]
As I was reworking the page, I realised that in multiple blocks, this happens: <img width="1391" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06c211e4f83b0a70f2b7f2d4de9e49011cdd58d8/issue.png" alt="issue.png" />

Not sure where the issue lies
